#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
RUN_USER="$(id -un)"
SERVICE_NAME="nespi-watcher.service"

cd "$PROJECT_DIR"

sudo apt-get update
sudo apt-get install -y python3 python3-venv python3-pip nmap

python3 -m venv .venv
source .venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt

if [ ! -f .env ]; then
  cat > .env << 'ENVEOF'
NETWORK_RANGE=192.168.1.0/24
NETWORK_RANGES=192.168.1.0/24
APP_HOST=0.0.0.0
APP_PORT=8080

SCAN_PROFILES=quick,deep
DEFAULT_SCAN_PROFILE=quick
NMAP_DEEP_PORTS=100
MAX_CONCURRENT_NMAP=1

PORT_SCAN_ON_NEW_DEVICE=false
PORT_SCAN_TOP_PORTS=20
PORT_SCAN_TIMEOUT=15
DNS_REVERSE_LOOKUP=false
VENDOR_LOOKUP_LOCAL=false
DEVICE_FINGERPRINT_ENABLED=true

TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=
WEBHOOK_URL=
WEBHOOK_SECRET=
TELEGRAM_MODE=summary
ALERT_MIN_NEW_DEVICES=1
ALERT_COOLDOWN_SECONDS=300
ALERT_UNKNOWN_ONLY=false
ALERT_SCAN_ERRORS=false
ALERT_OFFLINE_DEVICES=false
ALERT_IP_CHANGED=false
ALERT_OPEN_PORTS=false
ALERT_FINGERPRINT_CHANGED=false
ALERT_BATCH_WINDOW_SECONDS=60
QUIET_HOURS=
SENSITIVE_PORTS=22,23,445,3389

SCAN_TIMEOUT=60
MAX_SCAN_DURATION_SECONDS=300
AUTO_SCAN_ENABLED=true
SCAN_INTERVAL_SECONDS=600
STARTUP_SCAN_ENABLED=false
OFFLINE_AFTER_SECONDS=1800
NEW_DEVICE_GRACE_PERIOD_SECONDS=120
OFFLINE_GRACE_PERIOD_SECONDS=300
AUTO_RESCAN_AFTER_ERROR=false
RESCAN_DELAY_SECONDS=30

SCAN_API_KEY=
EXPORT_TOKEN=
ALLOWLIST_ONLY=false
BLOCKLIST_MACS=
BLOCKLIST_IPS=
SUSPECT_DEVICE_TAG=suspect
AUTO_TAG_BY_VENDOR=false
IGNORE_IPS=
IGNORE_MACS=
KNOWN_DEVICES_FILE=
DEVICE_ALIAS_ENABLED=true
EVENT_TYPES_FILTER=
DEVICE_RISK_SCORE_ENABLED=false
RISK_ALERT_THRESHOLD=70
SCAN_WINDOW=always

AUTO_BACKUP_ENABLED=false
BACKUP_RETENTION_DAYS=14
DB_VACUUM_SCHEDULE=off
WAL_MODE=true
API_RATE_LIMIT_SCAN_PER_MIN=3
READ_ONLY_API=false
MAINTENANCE_MODE=false
AUTH_BASIC_ENABLED=false
AUTH_USER=
AUTH_PASS_HASH=
CORS_ALLOWED_ORIGINS=
API_AUDIT_LOG=false
CHANGELOG_ENABLED=false
AUTO_UPDATE_CHECK=false

UI_THEME=cyber
SHOW_PRIVATE_INFO=true
UI_PAGE_SIZE_DEFAULT=100
UI_AUTO_REFRESH_SECONDS=15
TIMEZONE_DISPLAY=utc

HEALTH_REQUIRE_RECENT_SCAN=false
HEALTH_MAX_SCAN_AGE_SECONDS=1800

EXPORT_MAX_ROWS=5000
EXPORT_INCLUDE_NOTES=true
CSV_SEPARATOR=,
METRICS_ENABLED=true
CACHE_STATUS_SECONDS=5
NOTIFY_ON_FIRST_BOOT=false
HEARTBEAT_ENABLED=false
HEARTBEAT_INTERVAL_MIN=60
SCAN_JITTER_SECONDS=0
RANDOMIZE_NETWORK_ORDER=false
DEVICE_INACTIVE_DAYS_PURGE=0
EVENT_RETENTION_DAYS=0
SCAN_RETENTION_DAYS=0
DB_BACKUP_BEFORE_UPGRADE=true
DRY_RUN_SCAN=false
SAFE_MODE=false
TZ_OVERRIDE=
TIMESTAMP_FORMAT=iso
EXPORT_REDACT=false
AUDIT_HASH_CHAIN=false
MAX_EVENT_PER_DEVICE_PER_HOUR=20
BLOCKLIST_AUTO_EXPIRE_DAYS=0
REMOTE_IP_TRUST_HEADER=
SERVICE_BANNER=NESPi Watcher
UI_COMPACT_MODE=false

MAX_SCAN_HISTORY_ROWS=5000
LOG_LEVEL=INFO
LOG_RETENTION_DAYS=7
ENVEOF
fi

sed -e "s|__PROJECT_DIR__|$PROJECT_DIR|g" -e "s|__RUN_USER__|$RUN_USER|g" systemd/nespi-watcher.service > /tmp/nespi-watcher.service
sudo cp /tmp/nespi-watcher.service /etc/systemd/system/"$SERVICE_NAME"
sudo systemctl daemon-reload
sudo systemctl enable "$SERVICE_NAME"
sudo systemctl restart "$SERVICE_NAME"
